# -*- coding: utf-8 -*-
"""Q2_Narra_Chiva_ModularCalculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v41Xr-vzinaL-AAUzI6mJmxAQPF8xilm
"""

# Mini Program Modular Calculator

# Ask the user to input their numbers
num1 = float(input("Enter your first number!: "))
num2 = float(input("Enter your second number!: "))

# Ask the user which operation they want to use
print("Choose operation:")
print("1 - Addition")
print("2 - Subtraction")
print("3 - Multiplication")
print("4 - Division")

def is_valid_range(value):
  # returns true if value is between 1 and 4
  return 1 <= value <=4

value = float(input("Enter desired operation: "))

# Validation
if is_valid_range(value):
  print("Input is within valid range")
else:
  print("Input is not within valid range")

add_numbers = if (value) = 1
subtract_numbers if (value) = 2
multiply_numbers = if (value) = 3
divide_numbers if (value) = 4